Traceback (most recent call last):
  File "/home/ytanigaw/projects/nanopore/src/count.py", line 289, in <module>
    main()
  File "/home/ytanigaw/projects/nanopore/src/count.py", line 286, in main
    showname = args.showname)
  File "/home/ytanigaw/projects/nanopore/src/count.py", line 197, in show_counts_main
    data = process_entry(entry, ref, gap_char, qval_thr)
  File "/home/ytanigaw/projects/nanopore/src/count.py", line 119, in process_entry
    gap_char = gap_char)
  File "/home/ytanigaw/projects/nanopore/src/count.py", line 55, in retrieve_alignment
    aln_ref.append(ref[ptr_ref])
IndexError: string index out of range
